[package]
name = "xivdb"
version = "0.1.0"
authors = ["Kyle Clemens <me@kyleclemens.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.10"
hyper = "0.10"
hyper-rustls = "0.6"
url = "1.4"
