use kind::patch::XivDbPatch;

use serde_json::Value;

#[derive(Debug, Deserialize)]
pub struct XivDbFate {
  pub class_level: u64,
  pub class_level_max: u64,
  pub event_item: Option<Value>,
  pub help: String,
  pub help_cns: Option<String>,
  pub help_de: String,
  pub help_en: String,
  pub help_fr: String,
  pub help_ja: String,
  pub icon: String,
  pub icon_small: String,
  pub id: u64,
  pub lodestone_id: Option<String>,
  pub lodestone_type: Option<String>,
  pub map: Option<String>,
  pub name: String,
  pub name_cns: String,
  pub name_de: String,
  pub name_en: String,
  pub name_fr: String,
  pub name_ja: String,
  pub objective: u64,
  pub objective_0: String,
  pub objective_0_cns: Option<String>,
  pub objective_0_de: String,
  pub objective_0_en: String,
  pub objective_0_fr: String,
  pub objective_0_ja: String,
  pub objective_1: String,
  pub objective_1_cns: Option<String>,
  pub objective_1_de: String,
  pub objective_1_en: String,
  pub objective_1_fr: String,
  pub objective_1_ja: String,
  pub objective_2: String,
  pub objective_2_cns: Option<String>,
  pub objective_2_de: String,
  pub objective_2_en: String,
  pub objective_2_fr: String,
  pub objective_2_ja: String,
  pub objective_3: String,
  pub objective_3_cns: Option<String>,
  pub objective_3_de: String,
  pub objective_3_en: String,
  pub objective_3_fr: String,
  pub objective_3_ja: String,
  pub patch: XivDbPatch,
  pub placename: u64,
  pub position: String,
  pub url: String,
  pub url_api: String,
  pub url_type: String,
  pub url_xivdb: String,
  pub url_xivdb_de: String,
  pub url_xivdb_fr: String,
  pub url_xivdb_ja: String,
  pub xyz: u64,
  pub _cid: u64,
  pub _type: String,
}
